# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwentyPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
